In [1]:
# alternate strategy: https://stackoverflow.com/questions/1471994/what-is-setup-py --> making this shit a module to install
import sys
from pathlib import Path
PWD = Path.cwd()
# SRC = PWD.parent / 'src'
# sys.path.append(SRC)
from src.envs.yahtzee_env import YahzeeEnv
from gym.spaces import flatdim, flatten, flatten_space
import numpy as np

In [2]:
env = YahzeeEnv(num_dice=3, game_length='full', scoring_options='upper')

In [20]:
mask = np.array([1,1,0,0,0,1], dtype=np.int8)
env.observation_space['rolls'].sample(mask=(mask, mask, mask))

array([0, 5, 5], dtype=int64)

In [21]:
env.observation_space['scored_options'].sample(mask=np.array([1,1,0,0,0,0], dtype=np.int8))

array([1, 1, 0, 0, 0, 0], dtype=int8)

In [33]:
space = env.observation_space['scored_options']
sample = space.sample()
print(flatten(space, sample))
print(flatdim(space))
print(sample)

[0 1 0 1 1 0]
6
[0 1 0 1 1 0]
